# Generated by Django 4.2 on 2024-08-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactusmmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsmModel',
            new_name='ContactUsModel',
        ),
    ]
