# Generated by Django 4.2 on 2024-08-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_contactusmmodel_contactusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='code',
            field=models.CharField(default=0, max_length=9, verbose_name='کد پیگیری'),
            preserve_default=False,
        ),
    ]
