# Generated by Django 4.2 on 2024-08-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactusmodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='shape',
        ),
        migrations.DeleteModel(
            name='ProductRateModel',
        ),
    ]
