# Generated by Django 4.2 on 2024-08-10 16:20

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_productmodel_shape_delete_productratemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[store.models.is_number], verbose_name='قیمت پایه'),
        ),
    ]
