# Generated by Django 4.2 on 2024-08-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productmodel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShapeModel',
        ),
    ]
