# Generated by Django 4.2 on 2024-08-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_shapemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='value_added',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productpricemodel', verbose_name='محصول'),
        ),
    ]
