# Generated by Django 4.2 on 2024-08-12 14:55

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_invoicemodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='on_sale',
            field=models.CharField(default=0, max_length=12, validators=[store.models.is_number], verbose_name='تخفیف'),
            preserve_default=False,
        ),
    ]
