# Generated by Django 4.2 on 2024-08-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tokenmodel_recid'),
        ('store', '0012_invoiceitemmodel_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.addressmodel', verbose_name='آدرس'),
        ),
    ]
