# Generated by Django 4.2 on 2024-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_invoicemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
