# Generated by Django 4.2 on 2024-08-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_invoiceitemmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('authority', models.CharField(max_length=36, verbose_name='شناسه مرجع')),
                ('status', models.IntegerField(max_length=3, verbose_name='وضعیت')),
                ('refid', models.IntegerField(verbose_name='شماره تراکنش خرید')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره تماس خریدار')),
                ('email', models.CharField(max_length=100, verbose_name='ایمیل خریدار')),
                ('description', models.CharField(max_length=150, verbose_name='توضیحات')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.invoicemodel', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'فیش پرداخت',
                'verbose_name_plural': 'فیش\u200cهای پرداخت',
                'ordering': ['-created_date'],
            },
        ),
    ]
