# Generated by Django 4.2 on 2024-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_paymentmodel_amount_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
