# Generated by Django 4.2 on 2024-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_invoicemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='state',
            field=models.CharField(choices=[('wait', 'در انتظار پرداخت'), ('deposit', 'پیش پرداخت'), ('paid', 'پرداخت شده')], default='wait', max_length=50, verbose_name='وضعیت'),
        ),
    ]
