# Generated by Django 4.2 on 2024-09-04 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_managementnumbersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
